Repository securedevteam/social-media-dashboard, pull requests merged in 2020-05, with the labels that each got.

#4 Implemented basic authentication functionality
  src/SocialMediaDashboard.Common/Class1.cs
  src/SocialMediaDashboard.Common/DTO/UserDTO.cs
  src/SocialMediaDashboard.Common/Helpers/ApplicationSettings.cs
  src/SocialMediaDashboard.Common/Interfaces/IHasDbIdentity.cs
  src/SocialMediaDashboard.Common/Interfaces/IRepository.cs
  src/SocialMediaDashboard.Common/Interfaces/IUserService.cs
  src/SocialMediaDashboard.Data/Class1.cs
  src/SocialMediaDashboard.Data/Context/ApplicationContext.cs
  src/SocialMediaDashboard.Data/Extensions/DataServiceCollectionExtension.cs
  src/SocialMediaDashboard.Data/Repository/Repository.cs
  src/SocialMediaDashboard.Data/SocialMediaDashboard.Data.csproj
  src/SocialMediaDashboard.Domain/Class1.cs
  src/SocialMediaDashboard.Domain/Models/Media.cs
  src/SocialMediaDashboard.Domain/Models/Statistic.cs
  src/SocialMediaDashboard.Domain/Models/User.cs
  src/SocialMediaDashboard.Domain/SocialMediaDashboard.Domain.csproj
  src/SocialMediaDashboard.Logic/Class1.cs
  src/SocialMediaDashboard.Logic/Extensions/LogicServiceCollectionExtension.cs
  src/SocialMediaDashboard.Logic/Services/UserService.cs
  src/SocialMediaDashboard.Logic/SocialMediaDashboard.Logic.csproj
  src/SocialMediaDashboard.WebAPI/Controllers/UsersController.cs
  src/SocialMediaDashboard.WebAPI/Controllers/WeatherForecastController.cs
  src/SocialMediaDashboard.WebAPI/Extensions/WebServiceCollectionExtension.cs
  src/SocialMediaDashboard.WebAPI/Program.cs
  src/SocialMediaDashboard.WebAPI/Properties/launchSettings.json
  src/SocialMediaDashboard.WebAPI/SocialMediaDashboard.WebAPI.csproj
  src/SocialMediaDashboard.WebAPI/Startup.cs
  src/SocialMediaDashboard.WebAPI/ViewModels/LoginViewModel.cs
  src/SocialMediaDashboard.WebAPI/ViewModels/RegistrationViewModel.cs
  src/SocialMediaDashboard.WebAPI/ViewModels/ResponseViewModel.cs
  src/SocialMediaDashboard.WebAPI/WeatherForecast.cs
  src/SocialMediaDashboard.WebAPI/appsettings.Development.json
  src/SocialMediaDashboard.WebAPI/appsettings.json
Labels: enhancement

#6 feat: add comment
  src/SocialMediaDashboard.WebApp/ClientApp/src/store/saga.ts
Labels: documentation

#8 Remove SPA project
  SocialMediaDashboard.sln
  src/SocialMediaDashboard.WebApp/.gitignore
  src/SocialMediaDashboard.WebApp/ClientApp/.eslintrc.json
  src/SocialMediaDashboard.WebApp/ClientApp/.gitignore
  src/SocialMediaDashboard.WebApp/ClientApp/.vscode/launch.json
  src/SocialMediaDashboard.WebApp/ClientApp/.vscode/settings.json
  src/SocialMediaDashboard.WebApp/ClientApp/README.md
  src/SocialMediaDashboard.WebApp/ClientApp/package-lock.json
  src/SocialMediaDashboard.WebApp/ClientApp/package.json
  src/SocialMediaDashboard.WebApp/ClientApp/public/favicon.ico
  src/SocialMediaDashboard.WebApp/ClientApp/public/index.html
  src/SocialMediaDashboard.WebApp/ClientApp/public/manifest.json
  src/SocialMediaDashboard.WebApp/ClientApp/src/App.test.tsx
  src/SocialMediaDashboard.WebApp/ClientApp/src/App.tsx
  src/SocialMediaDashboard.WebApp/ClientApp/src/baseComponents/baseInput/index.tsx
  src/SocialMediaDashboard.WebApp/ClientApp/src/baseComponents/baseLabel/index.tsx
  src/SocialMediaDashboard.WebApp/ClientApp/src/baseComponents/baseLink/index.tsx
  src/SocialMediaDashboard.WebApp/ClientApp/src/components/autorisation/actionTypes.ts
  src/SocialMediaDashboard.WebApp/ClientApp/src/components/autorisation/actions.ts
  src/SocialMediaDashboard.WebApp/ClientApp/src/components/autorisation/index.tsx
  src/SocialMediaDashboard.WebApp/ClientApp/src/components/autorisation/reducer.ts
  src/SocialMediaDashboard.WebApp/ClientApp/src/components/autorisation/saga.ts
  src/SocialMediaDashboard.WebApp/ClientApp/src/components/autorisation/style.scss
  src/SocialMediaDashboard.WebApp/ClientApp/src/components/footer/index.tsx
  src/SocialMediaDashboard.WebApp/ClientApp/src/components/home/about.tsx
  src/SocialMediaDashboard.WebApp/ClientApp/src/components/home/index.tsx
  src/SocialMediaDashboard.WebApp/ClientApp/src/components/home/styles/home.scss
  src/SocialMediaDashboard.WebApp/ClientApp/src/components/layout/index.tsx
  src/SocialMediaDashboard.WebApp/ClientApp/src/components/navMenu/index.tsx
  src/SocialMediaDashboard.WebApp/ClientApp/src/components/navMenu/style.scss
  src/SocialMediaDashboard.WebApp/ClientApp/src/components/socialNetworkItem/index.tsx
  src/SocialMediaDashboard.WebApp/ClientApp/src/index.tsx
  src/SocialMediaDashboard.WebApp/ClientApp/src/react-app-env.d.ts
  src/SocialMediaDashboard.WebApp/ClientApp/src/registerServiceWorker.ts
  src/SocialMediaDashboard.WebApp/ClientApp/src/store/configureStore.ts
  src/SocialMediaDashboard.WebApp/ClientApp/src/store/index.ts
  src/SocialMediaDashboard.WebApp/ClientApp/src/store/saga.ts
  src/SocialMediaDashboard.WebApp/ClientApp/src/styles/main.scss
  src/SocialMediaDashboard.WebApp/ClientApp/tsconfig.json
  src/SocialMediaDashboard.WebApp/Pages/Error.cshtml
  src/SocialMediaDashboard.WebApp/Pages/Error.cshtml.cs
  src/SocialMediaDashboard.WebApp/Pages/_ViewImports.cshtml
  src/SocialMediaDashboard.WebApp/Program.cs
  src/SocialMediaDashboard.WebApp/Properties/launchSettings.json
  src/SocialMediaDashboard.WebApp/SocialMediaDashboard.WebApp.csproj
  src/SocialMediaDashboard.WebApp/Startup.cs
  src/SocialMediaDashboard.WebApp/appsettings.Development.json
  src/SocialMediaDashboard.WebApp/appsettings.json
Labels: bug

#9 Implemented Serilog functionality
  src/SocialMediaDashboard.WebAPI/Program.cs
  src/SocialMediaDashboard.WebAPI/SocialMediaDashboard.WebAPI.csproj
  src/SocialMediaDashboard.WebAPI/Startup.cs
  src/SocialMediaDashboard.WebAPI/appsettings.json
Labels: enhancement

#10 Implemented Health Check functionality
  src/SocialMediaDashboard.WebAPI/Extensions/WebServiceCollectionExtension.cs
  src/SocialMediaDashboard.WebAPI/Startup.cs
Labels: enhancement

#12 Intermediate merge #1
  .dockerignore
  .gitignore
  Dockerfile
  SocialMediaDashboard.sln
  src/SocialMediaDashboard.Common/Class1.cs
  src/SocialMediaDashboard.Common/DTO/ResponseDTO.cs
  src/SocialMediaDashboard.Common/DTO/TokenDTO.cs
  src/SocialMediaDashboard.Common/DTO/UserDTO.cs
  src/SocialMediaDashboard.Common/Enums/Roles.cs
  src/SocialMediaDashboard.Common/Helpers/ApplicationSettings.cs
  src/SocialMediaDashboard.Common/Interfaces/IHasDbIdentity.cs
  src/SocialMediaDashboard.Common/Interfaces/IRepository.cs
  src/SocialMediaDashboard.Common/Interfaces/IUserService.cs
  src/SocialMediaDashboard.Data/Class1.cs
  src/SocialMediaDashboard.Data/Configurations/MediaConfiguration.cs
  src/SocialMediaDashboard.Data/Configurations/StatisticConfiguration.cs
  src/SocialMediaDashboard.Data/Configurations/UserConfiguration.cs
  src/SocialMediaDashboard.Data/Context/ApplicationContext.cs
  src/SocialMediaDashboard.Data/Extensions/DataServiceCollectionExtension.cs
  src/SocialMediaDashboard.Data/Migrations/20200509173732_Init.Designer.cs
  src/SocialMediaDashboard.Data/Migrations/20200509173732_Init.cs
  src/SocialMediaDashboard.Data/Migrations/ApplicationContextModelSnapshot.cs
  src/SocialMediaDashboard.Data/Repository/Repository.cs
  src/SocialMediaDashboard.Data/SocialMediaDashboard.Data.csproj
  src/SocialMediaDashboard.Domain/Class1.cs
  src/SocialMediaDashboard.Domain/Models/Media.cs
  src/SocialMediaDashboard.Domain/Models/Statistic.cs
  src/SocialMediaDashboard.Domain/Models/User.cs
  src/SocialMediaDashboard.Domain/SocialMediaDashboard.Domain.csproj
  src/SocialMediaDashboard.Logic/Class1.cs
  src/SocialMediaDashboard.Logic/Extensions/LogicServiceCollectionExtension.cs
  src/SocialMediaDashboard.Logic/Services/UserService.cs
  src/SocialMediaDashboard.Logic/SocialMediaDashboard.Logic.csproj
  src/SocialMediaDashboard.WebAPI/Controllers/UsersController.cs
  src/SocialMediaDashboard.WebAPI/Controllers/WeatherForecastController.cs
  src/SocialMediaDashboard.WebAPI/Extensions/InitialServicesScopeFactory.cs
  src/SocialMediaDashboard.WebAPI/Extensions/RuntimeMigration.cs
  src/SocialMediaDashboard.WebAPI/Extensions/WebServiceCollectionExtension.cs
  src/SocialMediaDashboard.WebAPI/Program.cs
  src/SocialMediaDashboard.WebAPI/Properties/launchSettings.json
  src/SocialMediaDashboard.WebAPI/SocialMediaDashboard.WebAPI.csproj
  src/SocialMediaDashboard.WebAPI/Startup.cs
  src/SocialMediaDashboard.WebAPI/ViewModels/LoginViewModel.cs
  src/SocialMediaDashboard.WebAPI/ViewModels/ProfileViewModel.cs
  src/SocialMediaDashboard.WebAPI/ViewModels/RegistrationViewModel.cs
  src/SocialMediaDashboard.WebAPI/ViewModels/ResponseViewModel.cs
  src/SocialMediaDashboard.WebAPI/WeatherForecast.cs
  src/SocialMediaDashboard.WebAPI/appsettings.Development.json
  src/SocialMediaDashboard.WebAPI/appsettings.json
Labels: enhancement
